version: '3'

services:
  db:
    image: mysql:8
    restart: always
    container_name: db_mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - dev
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
          - db
        environment:
          PMA_HOST: db
          PMA_PORT: 3306
          PMA_ARBITRARY: 1
        restart: always
        ports:
          - 8081:80
        networks:
          - dev
  maildev:
    image: maildev/maildev
    container_name: maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8080:80"
    restart: always
    networks:
      - dev
  www:
    build: php
    container_name: www
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    depends_on:
      - db
    links:
      - db
    restart: always
    networks:
      - dev
networks:
  dev:
volumes:
  my-db:
