name: Symfony CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          "echo ${{ secrets.PASSWORD }} | sudo -S git pull"
          cd ${{ secrets.PROJECT_PATH }}
          composer install
          npm run dev
          php bin/console cache:clear
          php bin/console doctrine:schema:update --force
          php bin/console cache:clear
          php bin/console cache:warmup