name: Symfony CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          sudo git pull origin main
          sudo composer install
          sudo npm run dev
          sudo php bin/console cache:clear
          sudo php bin/console doctrine:schema:update --force
          sudo php bin/console cache:clear
          sudo php bin/console cache:warmup